#spring:


  #security:
    # oauth2:
      #client:
      # registration:
        #   google:
          #    client-id: 725273948009-k8rs4t44gbqvtqctrahmcgb8iiam4ovc.apps.googleusercontent.com
          #   client-secret: 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
         #   redirectUri: http://localhost:8080/signup
          #   scope: openid,profile,email
#  resource-server:
#   jwt:
#     issuer-uri: https://accounts.google.com
#    jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs





#ddl-auto: create


